{% set name = "torch-geometric-temporal" %}
{% set version = "0.37" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torch_geometric_temporal-{{ version }}.tar.gz
  sha256: ed5ea5c3571449ae01defd5a578a20a3fc990ca8e76cac69fb66e933106c2e84

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - decorator ==4.4.2
    - numpy
    - python >=3.6
    - scipy
    - six
    - pytorch
    - pytorch_cluster
    - pytorch_geometric
    - pytorch_scatter
    - pytorch_sparse
    - pytorch_spline_conv
    - tqdm

test:
  imports:
    - torch_geometric_temporal
    - torch_geometric_temporal.dataset
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/benedekrozemberczki/pytorch_geometric_temporal
  summary: A Temporal Extension Library for PyTorch Geometric.
  license: MIT
  license_file: LICENSE 

extra:
  recipe-maintainers:
    - MoRoBe-Work
